<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Vehicles\TrafficFineManagement.Vehicles.Application\TrafficFineManagement.Vehicles.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Vehicles\TrafficFineManagement.Vehicles.Infrastructure\TrafficFineManagement.Vehicles.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="9.3.2" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
