<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TrafficFineManagement.TrafficFine.Application\TrafficFineManagement.TrafficFine.Application.csproj" />
    <ProjectReference Include="..\TrafficFineManagement.TrafficFine.Domain\TrafficFineManagement.TrafficFine.Domain.csproj" />
    <ProjectReference Include="..\..\Vehicles\TrafficFineManagement.Vehicles.IntegrationEvents\TrafficFineManagement.Vehicles.IntegrationEvents.csproj" />
    <ProjectReference Include="..\..\Users\TrafficFineManagement.Users.IntegrationEvents\TrafficFineManagement.Users.IntegrationEvents.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\TrafficFineManagement.Infrastructure\TrafficFineManagement.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.11" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.19.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
