<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TrafficFineManagement.Vehicles.Application\TrafficFineManagement.Vehicles.Application.csproj" />
    <ProjectReference Include="..\TrafficFineManagement.Vehicles.Domain\TrafficFineManagement.Vehicles.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\TrafficFineManagement.Infrastructure\TrafficFineManagement.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
