<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TrafficFineManagement.Vehicles.Application\TrafficFineManagement.Vehicles.Application.csproj" />
    <ProjectReference Include="..\TrafficFineManagement.Vehicles.Domain\TrafficFineManagement.Vehicles.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\TrafficFineManagement.Infrastructure\TrafficFineManagement.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
